### PR TITLE
Code split zxcvbn

### PR DESCRIPTION
**Pull request by phyrog**
zxcvbn is a relatively large library (~300kb gzipped; the rest of the code is 220kb gzipped) that we only use in one position (show the password strength bar), so it makes sense to only load it when we actually need it. This also improves cachability for that library.

### CODE REVIEW

**Comment by eugenk** [comment]
How does this work in production? Does a second js file get built only for der zxcvbn lib that gets loaded when the `import` statement is hit?

How does this work in testing? Looks like the coverage decreased...

**Comment by phyrog** [comment]
Yup, that's how it works. Coverage decreased on one line (I think) that is basically a stub for the validation function while the lib is not loaded. I'm honestly not sure if and how to test that, since it obviously loads the lib too fast to run the stub in tests.

**Comment by eugenk** [comment]
Ok. Is there something like `:nocov:` for our coverage lib?

**Comment by phyrog** [comment]
I guess I could stub the `import` and return a rejected promise, so that the method isn't overwritten.

**Pull request merged**
